version: "3.3"
services:

  db:
    image: postgres:12
    volumes:
      - ml-server-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  backend:
    image: 'python-ml-server:latest'
    volumes:
      - ./app:/app
      - ./alembic:/alembic
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./
      dockerfile: application.dockerfile
    ports:
      - 80:80
    
volumes:
  ml-server-db-data:
